In [ ]:
# Celda para cargar librerias 
import os 
import math as m 
import random as rnd 
import time 
# Cargamos numpy 
import numpy as np


In [ ]:
help(np)

In [ ]:
# Creacion de objetos de tipo ndarray
a = np.array([12,16,9,23,32,0])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [ ]:
# Documentacion del metodo sum
help(a.sum)

Help on built-in function sum:

sum(...) method of numpy.ndarray instance
    a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)
    
    Return the sum of the array elements over the given axis.
    
    Refer to `numpy.sum` for full documentation.
    
    See Also
    --------
    numpy.sum : equivalent function



In [ ]:
a.sum()

92

In [ ]:
# Definamos un ndarray bidimensional
b = np.array([[1,4,7],[2,5,9]])

In [ ]:
print(b)

[[1 4 7]
 [2 5 9]]


In [ ]:
b

array([[1, 4, 7],
       [2, 5, 9]])

In [ ]:
b.sum()

28

In [ ]:
# Sumamos los elementos sobre las columnas 
b.sum(axis = 0)

array([ 3,  9, 16])

In [ ]:
# Sumamos los elementos sobre las filas 
b.sum(axis = 1)

array([12, 16])

In [ ]:
c = np.array([(0,1,0),(2,4,6),(1,1,1)])
print(c)

[[0 1 0]
 [2 4 6]
 [1 1 1]]


In [ ]:
# Sumamos por columnas
c.sum(axis = 0)

array([3, 6, 7])

In [ ]:
# Veamos el comportamiento de la funcion linspace
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [ ]:
# 50 puntos de -pi a pi
x1 = np.linspace(-m.pi,m.pi, 50 , endpoint= True)

In [ ]:
x1

array([-3.14159265, -3.01336438, -2.88513611, -2.75690784, -2.62867957,
       -2.5004513 , -2.37222302, -2.24399475, -2.11576648, -1.98753821,
       -1.85930994, -1.73108167, -1.60285339, -1.47462512, -1.34639685,
       -1.21816858, -1.08994031, -0.96171204, -0.83348377, -0.70525549,
       -0.57702722, -0.44879895, -0.32057068, -0.19234241, -0.06411414,
        0.06411414,  0.19234241,  0.32057068,  0.44879895,  0.57702722,
        0.70525549,  0.83348377,  0.96171204,  1.08994031,  1.21816858,
        1.34639685,  1.47462512,  1.60285339,  1.73108167,  1.85930994,
        1.98753821,  2.11576648,  2.24399475,  2.37222302,  2.5004513 ,
        2.62867957,  2.75690784,  2.88513611,  3.01336438,  3.14159265])

In [ ]:
len(x1)

50

In [ ]:
# Funcion zeros
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [ ]:
y1 = np.zeros(shape = 50)
print(y1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [ ]:
y2 = np.zeros(shape = (1,2))
print(y2)

[[0. 0.]]


In [ ]:
# Objeto tridimensional
y3 = np.zeros(shape = (2,3,2))
print(y3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
np.ones(shape = (2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
# Submodulo random 
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponen

In [ ]:
# Documentacion de la funcion random, del submodulo random, del modulo numpy
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [ ]:
np.random.random()

0.5308004562177056

In [ ]:
# Documentacion de la funcion triangular
help(np.random.triangular)

Help on built-in function triangular:

triangular(...) method of numpy.random.mtrand.RandomState instance
    triangular(left, mode, right, size=None)
    
    Draw samples from the triangular distribution over the
    interval ``[left, right]``.
    
    The triangular distribution is a continuous probability
    distribution with lower limit left, peak at mode, and upper
    limit right. Unlike the other distributions, these parameters
    directly define the shape of the pdf.
    
    .. note::
        New code should use the ``triangular`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    left : float or array_like of floats
        Lower limit.
    mode : float or array_like of floats
        The value where the peak of the distribution occurs.
        The value must fulfill the condition ``left <= mode <= right``.
    right : float or array_like of floats
        Upper limit, must be larger tha

In [ ]:
t1 = np.random.triangular(2.8, 3.23, 9.81, (3,3))
print(t1)

[[8.412253   3.33567082 9.26137313]
 [5.43882587 4.30772332 6.73396117]
 [3.64048097 7.75092998 4.02133034]]


In [ ]:
# Dado un objeto de tipo ndarray, tenemos a la mano algunos metodos informativos
print(t1.shape)
# Es una matriz de dimension 3x3

(3, 3)


In [ ]:
y1.shape

(50,)

In [ ]:
# Notar que el metodo shape retorna una tupla, y como  bien sabemos podemos acceder
# a los elementos de esa tupla
NumFilas = t1.shape[0]
NumColumnas = t1.shape[1]

In [ ]:
y3.shape

(2, 3, 2)

In [ ]:
# Numero de dimensiones del objeto 
y1.ndim

1

In [ ]:
y3.ndim

3

In [ ]:
# Tipo de dato de cada elemento de un objeto de tipo ndarray
t1.dtype

dtype('float64')

In [ ]:
# Definamos un vector con componentes bool
b1 = np.array([True, True, False, False, True, True ])
print(b1)

[ True  True False False  True  True]


In [ ]:
b1.shape

(6,)

In [ ]:
b1.ndim

1

In [ ]:
b1.dtype

dtype('bool')

In [ ]:
# acceso a las componentes de un objeto de tipo ndarray
c[0,0]

0

In [ ]:
c[0, 2]

0

In [ ]:
# la 2da columna 
c[:,1]

array([1, 4, 1])

In [ ]:
c

array([[0, 1, 0],
       [2, 4, 6],
       [1, 1, 1]])

In [ ]:
# la 3era columna 
c[:,2]

array([0, 6, 1])

In [ ]:
# CReemos un objeto de tipo ndarray de tamaño 6x6
D = np.random.chisquare(12.4, (6,6))

In [ ]:
D

array([[ 7.10439406, 10.94111842,  6.98641479, 12.13808862, 16.97519209,
        18.58002177],
       [21.82356024, 10.39429974,  6.1060043 ,  6.66360671, 11.00995866,
        10.85011881],
       [ 5.24781607, 11.86726459, 23.04259648, 12.8673483 , 14.97948517,
        17.36799335],
       [ 9.2188697 ,  6.08737562,  7.45975545, 11.02052762, 13.70832138,
        11.48046471],
       [14.74223783, 14.68436319, 14.96497659, 28.54855624,  9.25374573,
        19.72688132],
       [ 8.20678716,  7.41882941, 22.62495539, 13.46789174,  9.23622579,
         8.92666029]])

In [ ]:
# Deseo obtener las columnas 2,3 y 4
E = D[:, [2,3,4]]

In [ ]:
# Funciones de agregacion
D.sum(axis = 0)

array([66.34366507, 61.39325097, 81.18470299, 84.70601923, 75.16292882,
       86.93214025])

In [ ]:
# Calcular la suma de las filas de E
E.sum(axis = 1)

array([36.0996955 , 23.77956966, 50.88942996, 32.18860444, 52.76727856,
       45.32907291])

In [ ]:
# Calculemos la suma de las de columnas de E
E.sum(axis = 0)

array([81.18470299, 84.70601923, 75.16292882])

In [ ]:
# Calculo del promedio aritmetido : metodo mean
help(E.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [ ]:
# Retorna el promedio para cada fila 
E.mean(axis = 1)

array([12.03323183,  7.92652322, 16.96314332, 10.72953481, 17.58909285,
       15.10969097])

In [ ]:
# Calculo del promedio para cada columna 
E.mean(axis = 0)

array([13.53078383, 14.11766987, 12.5271548 ])

In [ ]:
help(E.min)

Help on built-in function min:

min(...) method of numpy.ndarray instance
    a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the minimum along a given axis.
    
    Refer to `numpy.amin` for full documentation.
    
    See Also
    --------
    numpy.amin : equivalent function



In [ ]:
help(E.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the maximum along a given axis.
    
    Refer to `numpy.amax` for full documentation.
    
    See Also
    --------
    numpy.amax : equivalent function



In [ ]:
# Desviacion estandar
help(E.std)

Help on built-in function std:

std(...) method of numpy.ndarray instance
    a.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)
    
    Returns the standard deviation of the array elements along given axis.
    
    Refer to `numpy.std` for full documentation.
    
    See Also
    --------
    numpy.std : equivalent function



In [ ]:
# Desviacion estandar de cada columna 
E.std(axis = 0)


array([7.18852034, 6.82287924, 2.9166596 ])

In [ ]:
# Desviacion estandar para cada fila 
E.std(axis = 1)

4.482494414382033

In [ ]:
E[E > 9.3]

array([12.13808862, 16.97519209, 11.00995866, 23.04259648, 12.8673483 ,
       14.97948517, 11.02052762, 13.70832138, 14.96497659, 28.54855624,
       22.62495539, 13.46789174])

In [ ]:
Q = np.random.normal(loc = 12.4, scale = 9.2, size = (4,4))
P = np.random.normal(loc = 12.4, scale = 9.2, size = (4,4))
print(P)
print(Q)

[[ 3.70317078 12.27390527  9.87364181 11.31392418]
 [12.77949071 -1.71488487  5.21402941  7.38716065]
 [ 1.06980561  6.63099927  7.83720248 -1.9868929 ]
 [21.51612758  2.13786015  0.49950079  5.26854804]]
[[13.741292   12.09728498 13.32697657  9.10643799]
 [12.41865501 10.10005178 -2.59234171  8.71685569]
 [11.00953709  4.90549771 17.8210189  30.12537797]
 [-5.67827168 13.58471747  0.2569123   8.1814387 ]]


In [ ]:
# Operacion elemento a elemento
# R[i,j] = P[i,j] + Q[i,j]

R = P + Q

In [ ]:
# Operacion elemento a elemento
# T[i,j] = P[i,j] - Q[i,j]


T = P - Q
print(T)

[[-10.03812122   0.17662029  -3.45333476   2.20748619]
 [  0.3608357  -11.81493665   7.80637111  -1.32969505]
 [ -9.93973148   1.72550156  -9.98381643 -32.11227088]
 [ 27.19439926 -11.44685732   0.24258849  -2.91289066]]


In [ ]:
# Operacion elemento a elemento
# Prod[i,j] = P[i,j] * Q[i,j]


Prod = P*Q

In [ ]:
# Multiplicacion matricial
help(np.multiply)

In [ ]:
# multiplicacion matricial de P  y Q
M1 = np.multiply(P,Q)
print(M1)

[[ 5.08863509e+01  1.48480930e+02  1.31585793e+02  1.03029549e+02]
 [ 1.58704086e+02 -1.73204260e+01 -1.35165459e+01  6.43928134e+01]
 [ 1.17780646e+01  3.25283517e+01  1.39666933e+02 -5.98558997e+01]
 [-1.22174418e+02  2.90422262e+01  1.28327900e-01  4.31043028e+01]]


In [ ]:
# Submodulo de algebra lineal
help(np.linalg)

In [ ]:
# lista de funciones del submodulo de algebra lineal 
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [ ]:
# Documentacion de la funcion inv
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), 

In [ ]:
# Documentacion de la funcion pinv
help(np.linalg.pinv)

Help on function pinv in module numpy.linalg:

pinv(a, rcond=1e-15, hermitian=False)
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
    
    Calculate the generalized inverse of a matrix using its
    singular-value decomposition (SVD) and including all
    *large* singular values.
    
    .. versionchanged:: 1.14
       Can now operate on stacks of matrices
    
    Parameters
    ----------
    a : (..., M, N) array_like
        Matrix or stack of matrices to be pseudo-inverted.
    rcond : (...) array_like of float
        Cutoff for small singular values.
        Singular values less than or equal to
        ``rcond * largest_singular_value`` are set to zero.
        Broadcasts against the stack of matrices.
    hermitian : bool, optional
        If True, `a` is assumed to be Hermitian (symmetric if real-valued),
        enabling a more efficient method for finding singular values.
        Defaults to False.
    
        .. versionadded:: 1.17.0
    
    Returns
    -

In [ ]:
# Generemos matrices de tamño/dimension 100000x100000 
# Calculemos sus inversas : usando inv y pinv 
# Y midamos los tiempos de unas 500 veces

n = 500
NumVeces = 500

NumCorrectas1 = 0
INICIO1 = time.time()
for v in range(500):
  A = np.random.triangular(1.3, 3.8, 12.9, (n,n))
  B = np.linalg.inv(A)
  Id = np.dot(A,B)
  V = np.identity(n) == Id
  if V.sum() == n*n:
    NumCorrectas1 = NumCorrectas1 +1
FIN1 = time.time()


NumCorrectas2 = 0
INICIO2 = time.time()
for v in range(NumVeces):
  A = np.random.triangular(1.3, 3.8, 12.9, (n,n))
  B = np.linalg.pinv(A)
  Id = np.dot(A,B)
  V = np.identity(n) == Id
  if V.sum() == n*n:
    NumCorrectas2 = NumCorrectas2 +1 
FIN2 = time.time()

print("Tiempo usando : inv " , FIN1-INICIO1)
print("Tiempo usando : pinv", FIN2-INICIO2)
print("El numero de correctas para inv es " ,NumCorrectas1)
print("El numero de correctas para pinv es " , NumCorrectas2)

Tiempo usando : inv  19.06002187728882
Tiempo usando : pinv 76.40150880813599
El numero de correctas para inv es  0
El numero de correctas para pinv es  0
